spring:
  application:
    name: microservice-1
  security:
    user:
      name: admin
      password: admin123

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/